### ISSUE TITLE
"fs" setting can not be saved

### ISSUE THREAD

**Issue by moetiker** [hadfl/lxadm#11]
lxadm edit hostname 

comes up with the entry:

.....
"fs" : [
         {
            "special" : "/share/z43-sales-tools",
            "options" : "[]",
            "type" : "lofs",
            "dir" : "/share/z43-sales-tools"
       }
...

without deleting the line 

        "options" : "[]",

I can not save the settings

**Comment by hadfl** [comment]
I'll close this as this is a bug in [Illumos::Zones](https://github.com/hadfl/Illumos-Zones)
