### ISSUE TITLE
lxadm does not respect dhcp as an input for "ips" - fails at validator

### ISSUE THREAD

**Issue by scosol** [hadfl/lxadm#17]
<img width="1025" alt="Screen Shot 2020-08-28 at 12 42 06 PM" src="https://user-images.githubusercontent.com/37912/91609304-fd414480-e92b-11ea-8ec2-39970c6dc198.png">

**Comment by hadfl** [comment]
As mentioned in https://github.com/hadfl/lxadm/issues/19 `lxadm` is unmaintaned and got superseded by [zadm](https://github.com/omniosorg/zadm).
