### ISSUE TITLE
lxadm does not respect "10.0.1.69" as valid input for "ips" - fails at validator

### ISSUE THREAD

**Issue by scosol** [hadfl/lxadm#19]
<img width="1025" alt="Screen Shot 2020-08-28 at 12 44 21 PM" src="https://user-images.githubusercontent.com/37912/91609457-53ae8300-e92c-11ea-8ea8-031fe2e81125.png">

**Comment by hadfl** [comment]
hi @scosol, 

IPs for lx zones must be configured in CIDR notation. Your example is lacking the subnet suffix.

Having said that, this project is unmaintaned, please have a look at [zadm](https://github.com/omniosorg/zadm) which is the successor of `lxadm`
